spring.application.name=tienda-mascotas

logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.datasource.url=jdbc:oracle:thin:@ri9zrk174m80adkh_high?TNS_ADMIN=/Users/sebastian/Wallet_RI9ZRK174M80ADKH
spring.datasource.username=MASCOTAS_ADMIN
spring.datasource.password=UsuarioAdmin.1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000